# Generated by Django 5.2.7 on 2025-11-23 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0005_coupon_coupon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='coupons',
            field=models.ManyToManyField(blank=True, related_name='carts', to='products.coupon'),
        ),
    ]
