# Generated by Django 5.2.7 on 2025-11-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_cart_coupon'),
        ('products', '0002_rename_code_coupon_coupon_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='coupon',
        ),
        migrations.AddField(
            model_name='cart',
            name='coupons',
            field=models.ManyToManyField(blank=True, to='products.coupon'),
        ),
    ]
