# Generated by Django 5.2.7 on 2025-12-27 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
