# Generated by Django 5.2.7 on 2026-01-06 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='district_id',
        ),
        migrations.RemoveField(
            model_name='address',
            name='province_id',
        ),
        migrations.RemoveField(
            model_name='address',
            name='ward_code',
        ),
    ]
