# Generated by Django 5.2.7 on 2026-01-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_address_district_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='district_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='province_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='ward_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
