# Generated by Django 5.2.7 on 2025-11-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Slide', max_length=100)),
                ('image', models.ImageField(upload_to='sliders')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
