# Generated by Django 5.2.7 on 2025-12-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Chờ xác nhận'), ('Confirmed', 'Đã xác nhận'), ('paid', 'Đã thanh toán'), ('shipped', 'Đang giao'), ('cancelled', 'Đã hủy')], default='Pending', max_length=20),
        ),
    ]
