# Generated by Django 5.2.7 on 2025-12-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Chờ xác nhận'), ('Confirmed', 'Đã xác nhận'), ('shipped', 'Đang giao'), ('paid', 'Đã thanh toán'), ('cancelled', 'Đã hủy'), ('completed', 'Hoàn thành')], default='Pending', max_length=20),
        ),
    ]
