# Generated by Django 5.2.7 on 2025-11-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='code',
            new_name='coupon_code',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='valid_from',
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_price',
            field=models.IntegerField(default=100, help_text='Số tiền giảm giá cố định (ví dụ: 10000 = 10.000đ)'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='minimum_amount',
            field=models.IntegerField(default=500, help_text='Số tiền tối thiểu của đơn hàng (ví dụ: 500000 = 500.000đ)'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Tắt/mở mã này thủ công'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(blank=True, help_text='Ngày mã hết hạn (để trống nếu không bao giờ hết hạn)', null=True),
        ),
    ]
