# Generated by Django 5.2.7 on 2025-12-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_updated_at_variant_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='original_price',
            field=models.IntegerField(default=0),
        ),
    ]
