# Generated by Django 5.2.7 on 2025-12-11 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_variant_original_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='variant_name',
        ),
    ]
