# Generated by Django 5.2.7 on 2025-11-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_coupon_usage_limit_per_user_couponusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_type',
            field=models.CharField(choices=[('shipping', 'Free Shipping'), ('amount', 'Giảm tiền trực tiếp'), ('percent', 'Giảm phần trăm')], default='amount', max_length=20),
        ),
    ]
