# Generated by Django 5.2.7 on 2025-12-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productimage_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorvariant',
            name='color_code',
            field=models.CharField(default='#000000', help_text='Hex color code (e.g., #FF5733)', max_length=7),
        ),
    ]
