# Generated by Django 5.2.7 on 2025-12-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_colorvariant_color_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorvariant',
            name='color_code',
            field=models.CharField(default='#000000', help_text='xanh:#1E3A5F, nâu:#8B5A3C, đen:#000000, trắng:#FFFFFF', max_length=7),
        ),
    ]
